"""Shared pieces of the pages' tables: where the fragments live, how numbers and dates print, the
MyST and Typst table wrappers, the three scenario runs the tables draw on, and the command line
every fragment writer shares (``fragments_main``, ``log_to_stdout``).

Every article uses this module, so it depends on ``econ_scenarios`` and on nothing else. That is
what lets a paper with no household model format a table without loading a solver it will never
call. Keep it that way. A table formatter that reaches for a solving package couples every
article cut from this repository to that package, whether or not the article solves anything.
"""

from __future__ import annotations

import argparse
import functools
import logging
import re
import sys
from pathlib import Path
from typing import TYPE_CHECKING

from econ_scenarios import EXTREME, MODEST, SUBSTANTIAL, Simulation, simulate

if TYPE_CHECKING:
    from collections.abc import Callable

FRAGMENTS = Path(__file__).resolve().parents[1] / "content" / "fragments"
CONTENT = FRAGMENTS.parent
# A table's caption lives in the page that includes it, as MyST comment lines above the include:
# ``% caption tbl-x``, then the caption over one or more ``%`` lines joined with a space (Alan,
# 2026-09-21). It renders nowhere; the float carries the reader's copy; ``--check`` holds them equal.
PAGE_CAPTION = re.compile(
    r"^% caption (tbl-[a-z0-9-]+)\n((?:%(?! caption tbl-)[ \t]+\S.*\n?)+)",
    re.MULTILINE,
)


def page_captions_in(text: str) -> dict[str, str]:
    """The table captions written in one page's text, by label."""
    return {
        label: " ".join(line.lstrip("%").strip() for line in lines.splitlines())
        for label, lines in PAGE_CAPTION.findall(text)
    }


@functools.cache
def page_captions() -> dict[str, tuple[Path, str]]:
    """Every table caption the pages write, by label, with the page it is in."""
    found: dict[str, tuple[Path, str]] = {}
    for page in sorted(CONTENT.glob("*.md")):
        for label, caption in page_captions_in(
            page.read_text(encoding="utf-8"),
        ).items():
            if label in found:
                msg = f"{label} is captioned in both {found[label][0].name} and {page.name}"
                raise LookupError(msg)
            found[label] = (page, caption)
    return found


def page_caption(label: str) -> str:
    """The caption the including page writes for the table ``label``."""
    if label not in page_captions():
        msg = f"no page writes '% caption {label}' and a '% <caption>' line above its include"
        raise LookupError(msg)
    return page_captions()[label][1]


NAMES = {"cognitive": "cognitive stayer", "other": "other-work stayer"}
TAIL_NAMES = {"frozen": "2030 gaps persist", "converge": "gaps close by 2035"}
SCENARIOS = {"modest": MODEST, "substantial": SUBSTANTIAL, "extreme": EXTREME}
CRRAS = (
    1.5,
    2.0,
    3.0,
    4.0,
    5.0,
)  # the preference sweep; 5 covers the low end of the evidence on the elasticity of intertemporal substitution
DISCOUNTS = (0.95, 0.96, 0.97)  # annual discount factors of the preference sweep
QUIZ_DISCOUNTS = (
    0.99,
    0.98,
    0.97,
    0.96,
    0.95,
    0.93,
    0.91,
)  # the quiz's patience answers
MONTHS = (
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
)


def number(x: float, digits: int = 1) -> str:
    """A number as the page prints it, with no negative zero."""
    text = f"{x:.{digits}f}"
    return text[1:] if text.startswith("-") and float(text) == 0.0 else text


# A table prints one decimal more than the prose quotes, so that a reader reproducing a table
# never faces the precision gap the reproduction report found in Korinek et al.'s Table 1, where one
# unprinted digit accounted for every miss. The prose keeps ``number``'s rounding for reading.
TABLE_EXTRA_DIGITS = 1


def cell(x: float, digits: int = 1) -> str:
    """A table cell: ``number`` at one more decimal than the prose prints the same quantity."""
    return number(x, digits + TABLE_EXTRA_DIGITS)


def date(t: float | None, missing: str = "at the limit") -> str:
    """A month of the run as "Month Year"."""
    if t is None:
        return missing
    k = round((t - 2024.0) * 12)
    return f"{MONTHS[k % 12]} {2024 + k // 12}"


# Both arguments are required, and were defaulted to a private package's report module until
# 2026-09-18. Defaults named that package in a module every cut carries, so the reproduction's
# public repository held a regeneration command for code it does not have.
def command(module: str, package: str) -> str:
    """The command that rewrites the fragments a module of ``package`` writes."""
    name = module[: -len(".py")].replace("/", ".")
    return f"cd code && uv run python -m {package}.{name} --write"


def header(module: str, package: str) -> str:
    return f"<!-- Generated by code/{package}/{module}; regenerate with: {command(module, package)} -->\n\n"


def log_to_stdout() -> None:
    """Log bare messages to stdout, over whatever handlers are already set up (HARK configures
    logging on import, which makes a plain ``basicConfig`` a no-op).
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(message)s",
        stream=sys.stdout,
        force=True,
    )


def fragments_main(
    description: str | None,
    fragments: Callable[[], dict[str, str]],
    rewrite: str,
    facts: Callable[[], dict[str, str]] | None = None,
) -> int:
    """The ``main`` of a module that writes fragments: ``--write`` rewrites them, ``--check`` fails
    if one differs from what ``fragments()`` computes now, naming the command ``rewrite`` that
    regenerates it, and ``--facts``, when the module has ``facts``, logs the numbers the prose
    quotes.
    """
    log_to_stdout()
    log = logging.getLogger(fragments.__module__)
    parser = argparse.ArgumentParser(description=description)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="rewrite the fragments")
    mode.add_argument(
        "--check",
        action="store_true",
        help="fail if a fragment is stale",
    )
    if facts is not None:
        mode.add_argument(
            "--facts",
            action="store_true",
            help="log the numbers the prose quotes",
        )
    args = parser.parse_args()
    if facts is not None and args.facts:
        for key, value in facts().items():
            log.info("%s: %s", key, value)
        return 0
    stale = []
    for name, text in fragments().items():
        path = FRAGMENTS / name
        if args.write:
            FRAGMENTS.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
            log.info("wrote %s", path)
        elif not path.exists() or path.read_text() != text:
            stale.append(name)
    if stale:
        log.error("stale fragments, regenerate with %s: %s", rewrite, ", ".join(stale))
        return 1
    return 0


def row(cells: list[str]) -> str:
    return "| " + " | ".join(cells) + " |"


# The pipe-table alignments the callers use, as LaTeX column letters. Only ``l c r`` appear: a
# ``p{}`` column forces a width, which is what made the wide tables wrap one word per line.
COLUMNS = {"---": "l", "--:": "r", ":--": "l", ":-:": "c"}

# A table overflows in one of two ways, and they want opposite repairs. Columns of prose cannot
# break at all under ``l``, so they take a ``p{}`` that wraps; columns of numbers are already
# narrow, so a table wide only because it has many of them is shrunk whole.
CHAR_PT = 4.0  # average character advance at \footnotesize
PADDING_PT = 12.0  # 2 \tabcolsep per column
TEXT_PT = 468.0  # text width of the arxiv_nips export, 6.5in on letter paper, the one PDF built
PROSE = 30  # a column whose longest cell reaches this many characters wraps instead of aligning
MIN_FRACTION = (
    0.10  # floor on a wrapped column, so a wide neighbour cannot squeeze it to nothing
)
HEAD_CHARS = 9  # a wrapped header gets at least this many characters a line


def widths(cells: list[list[str]]) -> list[int]:
    """The longest cell of each column, in characters, over the given rows."""
    return [max(len(c) for c in col) for col in zip(*cells, strict=True)]


def spec(align: list[str], head: list[str], rows: list[list[str]]) -> tuple[str, bool]:
    """The tabular's column spec, and whether the result still needs shrinking to the text width.

    Columns of prose become ``p{}`` and share whatever width the aligned columns leave them, in
    proportion to their own longest cell. A table that is wide only because its headers are
    longer than the numbers under them wraps those headers instead, over a ``p{}`` as wide as
    the numbers, so that the rows stay one line each and the type stays at its size. Only a
    table neither repair brings inside the text block is shrunk.
    """
    body = widths(rows) if rows else [0] * len(head)
    header = widths([head])
    prose = [i for i, n in enumerate(body) if n >= PROSE]
    natural = [max(body[i], header[i]) for i in range(len(head))]
    aligned = [i for i in range(len(head)) if i not in prose]
    used = sum(natural[i] * CHAR_PT for i in aligned) + PADDING_PT * len(head)
    wrapped: dict[int, float] = {}
    if used > TEXT_PT:
        for i in aligned:
            if header[i] > body[i]:
                chars = max(body[i], HEAD_CHARS)
                wrapped[i] = chars * CHAR_PT / TEXT_PT
                used -= (natural[i] - chars) * CHAR_PT
    free = 1.0 - used / TEXT_PT
    total = sum(body[i] for i in prose)
    letters = []
    for i, a in enumerate(align):
        if i in prose:
            fraction = max(free * body[i] / total, MIN_FRACTION)
            used += fraction * TEXT_PT
            letters.append(rf"p{{{fraction:.3f}\linewidth}}")
        elif i in wrapped:
            letters.append(rf"p{{{wrapped[i]:.3f}\linewidth}}")
        else:
            letters.append(COLUMNS[a])
    # The floor on a wrapped column can push the layout back past the text block, so the decision
    # to shrink is taken on the widths actually written, never on the ones first wanted.
    return "".join(letters), used > TEXT_PT


# Escapes for a cell outside its math. ``\`` is deliberately absent, since the only backslashes
# the reports emit are inside ``$...$``. A stray ``%`` would comment out the rest of the row.
ESCAPES = (
    ("&", r"\&"),
    ("%", r"\%"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
)


LATEX_COMMAND = re.compile(r"\\[A-Za-z]+(?:\{[^{}]*\})*")


def tex(cell: str) -> str:
    r"""A cell as LaTeX, escaping the prose and passing math and commands through untouched.

    Two things in a cell are already LaTeX and must survive: ``$...$`` math, and a command such as
    ``\\citet{key}``, which a caption needs because a MyST role inside a raw LaTeX body is never
    processed. Everything else is prose, where an unescaped ``%`` would comment out the rest of
    the row.
    """
    parts = cell.split("$")
    for i in range(0, len(parts), 2):  # even parts are outside math
        pieces = []
        last = 0
        for match in LATEX_COMMAND.finditer(parts[i]):
            pieces.append(escape(parts[i][last : match.start()]))
            pieces.append(match.group())
            last = match.end()
        pieces.append(escape(parts[i][last:]))
        parts[i] = "".join(pieces)
    return "$".join(parts)


def escape(prose: str) -> str:
    """Prose with every LaTeX special character escaped."""
    for plain, escaped in ESCAPES:
        prose = prose.replace(plain, escaped)
    return prose


# Typst markup: every character that would open markup inside a cell or caption. Backticks stay,
# since a code span is code in both languages.
TYPST_SPECIALS = "\\#*_@<>[]~$"
CITATION = re.compile(r"\\cite([tp])\{([^}]+)\}")
TYPST_ALIGN = {"---": "left", "--:": "right", ":--": "left", ":-:": "center"}
WIDE_COLUMNS = (
    8  # from here on a Typst table leaves the text column for the margin rail
)


def typ(cell: str) -> str:
    """A cell or caption as Typst markup: citations become ``#cite``, everything else is escaped."""
    parts = CITATION.split(cell)
    out = []
    for i in range(0, len(parts), 3):  # prose, then (form, key) pairs
        out.append("".join("\\" + c if c in TYPST_SPECIALS else c for c in parts[i]))
        if i + 2 < len(parts):
            form = ', form: "prose"' if parts[i + 1] == "t" else ""
            out.append(f"#cite(<{parts[i + 2]}>{form})")
    return "".join(out)


EM_PER_CHAR = 0.55  # a digit or lowercase letter at the table's size, in em


def typst_widths(align: list[str], head: list[str], rows: list[list[str]]) -> list[str]:
    """Typst column widths on the LaTeX layout's logic. An ``auto`` column takes the width of its
    longest unbroken cell, which for a column of numbers is its header, so the numbers would be
    in a column as wide as "Consumption, Jan 2024" while the row labels wrap. Numeric columns get
    a fixed width from their longest number or header word, so the header wraps instead; prose
    columns share the rest in proportion to their longest cell; row labels keep their natural
    width.
    """
    body = widths(rows) if rows else [0] * len(head)
    natural = []  # the column's longest cell or header word, in em
    out = []
    for i, a in enumerate(align):
        word = max(len(w) for w in head[i].split()) if head[i].split() else 1
        natural.append(max(body[i], word, HEAD_CHARS) * EM_PER_CHAR)
        if body[i] >= PROSE:
            out.append(f"{body[i]}fr")
        elif a == "--:":
            out.append(f"{natural[i]:.1f}em")
        else:
            out.append("auto")
    # A table with no fractional column takes its natural width, centered in the text column; in
    # the wide box that spans into the rail it lands off-center, so there the columns after the
    # first share the box in proportion to their natural widths, which keeps a wide header its room.
    if len(head) >= WIDE_COLUMNS and not any(w.endswith("fr") for w in out):
        out = ["auto", *(f"{w:.1f}fr" for w in natural[1:])]
    return out


def typst_table(
    head: list[str],
    rows: list[list[str]],
    caption: str,
    align: list[str],
) -> str:
    """The same table as a booktabs-style Typst figure in a colon-form raw block, which the Typst
    export renders and the site and the LaTeX export ignore.

    MyST also parses the raw LaTeX float into a table and renders that in Typst, with equal
    columns and no header row, so every page that includes these fragments opens with a Typst
    show rule that hides the parsed copies: they carry the ``kind: "table"`` string, the twins
    the ``table`` function, and MyST's own numbering of the parsed copies matches the twins'
    because they come in the same order. The twins carry no label, since the parsed copy keeps
    the one MyST's cross-references point at; it is placed out of the flow and hidden rather than
    dropped, so that the label still exists.
    """
    columns = ", ".join(typst_widths(align, head, rows))
    alignment = ", ".join(TYPST_ALIGN[a] for a in align)
    # A table with this many columns goes to the template's ``fullwidth``, which spans the margin
    # rail as well as the text column, caption included; ``float: false`` keeps it in the flow
    # after the sentence that introduces it, which a float does not.
    wide = len(head) >= WIDE_COLUMNS
    cells = [
        "      table.hline(stroke: 0.75pt),",
        "      table.header(" + ", ".join(f"[*{typ(h)}*]" for h in head) + "),",
        "      table.hline(stroke: 0.5pt),",
        *["      " + ", ".join(f"[{typ(c)}]" for c in r) + "," for r in rows],
        "      table.hline(stroke: 0.75pt),",
    ]
    open_figure, close_figure = (
        ("#fullwidth(float: false)[#figure(", ")]") if wide else ("#figure(", ")")
    )
    body = [
        open_figure,
        "  {",
        f"    set text(size: {7 if wide else 8}pt, hyphenate: false)",
        "    table(",
        f"      columns: ({columns}),",
        f"      align: ({alignment}),",
        "      stroke: none,",
        "      inset: (x: 4pt, y: 3pt),",
        *cells,
        "    )",
        "  },",
        f"  caption: [{typ(caption)}],",
        "  kind: table,",
        close_figure,
    ]
    return ":::{raw:typst}\n" + "\n".join(body) + "\n:::\n"


def table(
    head: list[str],
    rows: list[list[str]],
    caption: str,
    label: str,
    align: list[str] | None = None,
    *,
    module: str,
    package: str,
) -> str:
    r"""A booktabs float in a raw LaTeX block, referenced from the page as ``[](#label)``, followed
    by its Typst twin from ``typst_table``; numeric columns are right-aligned unless ``align``
    says otherwise.

    The LaTeX fence is the ARGUMENT form ```` ```{raw} latex ````, never the colon form
    ``:::{raw:latex}``. Measured on mystmd 1.10.1: the argument form stores the body in both
    ``value`` and ``tex``, so the float reaches the PDF verbatim while ``tex-to-myst`` also parses
    it into a real numbered table for the site; the colon form stores ``tex`` only and renders
    nothing on the web. Keep the column spec to ``l c r p{}``: the parser cannot read an ``array``
    spec such as ``>{\\centering\\arraybackslash}p{}`` and degrades the whole environment to bare
    macros. Nothing here may use a macro ``tex-to-myst`` does not know, such as ``\\setlength``,
    which raises ``Unhandled TEX conversion`` on every build.
    """
    align = ["---"] + ["--:"] * (len(head) - 1) if align is None else align
    columns, shrink = spec(align, head, rows)
    tabular = [
        rf"\begin{{tabular}}{{{columns}}}",
        r"\toprule",
        " & ".join(tex(h) for h in head) + r" \\",
        r"\midrule",
        *[" & ".join(tex(c) for c in r) + r" \\" for r in rows],
        r"\bottomrule",
        r"\end{tabular}",
    ]
    # Uncapped, the widest tabular ran 1228pt past the text block, which LaTeX reports only as an
    # Overfull \hbox in its log while the export still reports success. \resizebox scales up as
    # well as down, so it is applied only to a table no wrapped column can rescue.
    if shrink:
        tabular = [r"\resizebox{\textwidth}{!}{%", *tabular, r"}"]
    body = [
        r"\begin{table}",
        r"\centering",
        r"\footnotesize",
        rf"\caption{{{tex(caption)}}}",
        rf"\label{{{label}}}",
        *tabular,
        r"\end{table}",
    ]
    return (
        header(module, package)
        + "```{raw} latex\n"
        + "\n".join(body)
        + "\n```\n\n"
        + typst_table(head, rows, caption, align)
    )


@functools.cache
def scenarios() -> dict[str, Simulation]:
    return {s.name: simulate(s) for s in (MODEST, SUBSTANTIAL, EXTREME)}


__all__ = [
    "CRRAS",
    "DISCOUNTS",
    "FRAGMENTS",
    "MONTHS",
    "NAMES",
    "QUIZ_DISCOUNTS",
    "SCENARIOS",
    "TAIL_NAMES",
    "command",
    "date",
    "header",
    "number",
    "row",
    "scenarios",
    "table",
]
